// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalcPriceController from "./calc_price_controller"
application.register("calc-price", CalcPriceController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import DropDownLogController from "./drop_down_log_controller"
application.register("drop-down-log", DropDownLogController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
